server:
  port: 9000

jwt:
  secret: ${JWT_SECRET}

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://caseclarity-auth-service:8080
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /internal/auth/${segment}

        - id: evidence-service
          uri: http://caseclarity-evidence-service:8082
          predicates:
            - Path=/evidence/**

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

logging:
  level:
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: DEBUG
    org.springframework.security: DEBUG
