services:
  postgres:
    image: postgres:15
    container_name: caseclarity-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - caseclarity-net

  auth-service:
    build: ./caseclarity-auth-service
    container_name: caseclarity-auth-service
    env_file:
      - ./caseclarity-auth-service/.env
    depends_on:
      - postgres
    networks:
      - caseclarity-net

  api-gateway:
    build: ./caseclarity-api-gateway
    container_name: caseclarity-api-gateway
    ports:
      - "9000:8080"
    depends_on:
      - auth-service
    networks:
      - caseclarity-net

volumes:
  pgdata:

networks:
  caseclarity-net:
    driver: bridge
