services:
  postgres:
    image: postgres:15
    container_name: caseclarity-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    networks:
      - caseclarity-net

  auth-service:
    build:
      context: ./caseclarity-auth-service
      dockerfile: Dockerfile
    image: caseclarity-platform-auth-service
    container_name: caseclarity-auth-service
    ports:
      - "8080:8080"
    env_file:
      - ./caseclarity-auth-service/.env
    depends_on:
      - postgres
    networks:
      - caseclarity-net

  api-gateway:
    build:
      context: ./caseclarity-api-gateway
      dockerfile: Dockerfile
    image: caseclarity-platform-api-gateway
    container_name: caseclarity-api-gateway
    ports:
      - "9000:9000"
    env_file:
      - ./caseclarity-api-gateway/.env
    depends_on:
      - auth-service
    networks:
      - caseclarity-net

networks:
  caseclarity-net:
